### ISSUE TITLE
Ajax loader in the bad area

### ISSUE THREAD

**Issue by marcteyssier** [thecodingmachine/mouf-html.widgets.evolugrid#5]
When the infinity scroll is not enabled, the ajax loader is displayed at the bottom. The user don't see it.

**Comment by nguyenk** [comment]
I assume the issue is "When the infinity scroll is not enabled, the ajax loader is displayed at the bottom... ".

If yes, this one is fixed.

Anyway, on large paginations (100 items pages for example, the issue is the spin loader is not visible as it is set to top: 50% of the fader. Maybe it would be better to move it to a fixed distance trop top, like top: 20px or so ?
